 
POST http://localhost:8080/odata/v4/OrdersService/Orders
Content-Type: application/json
 Authorization: Basic max:pass@123
 
{
    "items" : [
        {
            "book_ID" : "abed2f7a-c50e-4bc5-89fd-9a00a54b4b16",
            "amount" : 4
        }
    ]
}
 
 
### Read Book
 
GET http://localhost:8080/odata/v4/BookService/Books(abed2f7a-c50e-4bc5-89fd-9a00a54b4b16)
Accept: application/json
 Authorization: Basic emma:pass@456
 
###
GET http://localhost:8080/odata/v4/OrdersService/Orders?$expand=items
Accept: application/json
Authorization: Basic emma:pass@456
 
 ###
GET http://localhost:8080/odata/v4/AdminService
Accept: application/json
Authorization: Basic emma:pass@456
